"""
Database — AICenter model and PostgreSQL setup
================================================
Stores AI design requests with their generated designs,
product references, and the final visualization.
"""
from __future__ import annotations

from typing import Optional

from sqlmodel import SQLModel, Field, create_engine, Session

import config


class AICenter(SQLModel, table=True):
    """Stores an AI design request and its outputs."""

    id: Optional[int] = Field(default=None, primary_key=True)
    user_idea: str = Field(
        ..., description="The user's design prompt / idea."
    )
    design_from_gemini: Optional[str] = Field(
        default=None,
        description="Base64-encoded design image generated by the AI.",
    )
    product_id: int = Field(
        ..., description="Reference to the Product in product_services."
    )
    final_product: Optional[str] = Field(
        default=None,
        description="Base64-encoded final visualization (design applied on product).",
    )
    status: str = Field(
        default="pending",
        description="Status: pending / approved / rejected.",
    )


# ---------------------------------------------------------------------------
# Engine & session
# ---------------------------------------------------------------------------

connection_string = str(config.AI_CENTER_DATABASE_URL).replace(
    "postgresql", "postgresql+psycopg2"
)

engine = create_engine(connection_string, connect_args={}, pool_recycle=300)


def create_db_and_tables() -> None:
    SQLModel.metadata.create_all(engine)


def get_session():
    with Session(engine) as session:
        yield session
